USE [master]
GO
/****** Объект:  Database [AutoPartsStore]    Дата создания скрипта: 05.07.2026 21:50:54 ******/ 
CREATE DATABASE [AutoPartsStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AutoPartsStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\AutoPartsStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AutoPartsStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\AutoPartsStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AutoPartsStore] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AutoPartsStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AutoPartsStore] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AutoPartsStore] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AutoPartsStore] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AutoPartsStore] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AutoPartsStore] SET ARITHABORT OFF 
GO
ALTER DATABASE [AutoPartsStore] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [AutoPartsStore] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AutoPartsStore] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AutoPartsStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AutoPartsStore] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AutoPartsStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AutoPartsStore] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AutoPartsStore] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AutoPartsStore] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AutoPartsStore] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AutoPartsStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AutoPartsStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AutoPartsStore] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AutoPartsStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AutoPartsStore] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AutoPartsStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AutoPartsStore] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AutoPartsStore] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AutoPartsStore] SET  MULTI_USER 
GO
ALTER DATABASE [AutoPartsStore] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AutoPartsStore] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AutoPartsStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AutoPartsStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AutoPartsStore] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AutoPartsStore] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [AutoPartsStore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [AutoPartsStore] SET QUERY_STORE = ON
GO
ALTER DATABASE [AutoPartsStore] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AutoPartsStore]
GO
/****** Объект:  Table [dbo].[Client]    Дата создания скрипта: 05.07.2026 21:50:54 ******/ 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Client](
	[ClientID] [uniqueidentifier] NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Phone] [varchar](12) NOT NULL,
	[Email] [varchar](100) NULL,
	[RegistrationDate] [datetime] NULL,
	[IsActive] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ClientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Phone] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Объект:  Table [dbo].[Orders]    Дата создания скрипта: 05.07.2026 21:50:55 ******/ 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[OrderID] [uniqueidentifier] NOT NULL,
	[OrderNumber] [int] NOT NULL,
	[ClientID] [uniqueidentifier] NOT NULL,
	[OrderDate] [datetime] NULL,
	[OrderPrice] [decimal](12, 2) NOT NULL,
	[IsPaid] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[OrderNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Объект:  Table [dbo].[Products]    Дата создания скрипта: 05.07.2026 21:50:55 ******/ 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductID] [int] IDENTITY(1,1) NOT NULL,
	[ProductGuid] [uniqueidentifier] NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[StockQuantity] [int] NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ProductGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Объект:  Table [dbo].[ProductSupplies]    Дата создания скрипта: 05.07.2026 21:50:55 ******/ 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductSupplies](
	[SupplyID] [int] IDENTITY(1,1) NOT NULL,
	[SupplierID] [int] NOT NULL,
	[ProductID] [int] NOT NULL,
	[SupplyDate] [datetime] NULL,
	[SupplyCount] [int] NOT NULL,
	[SupplyPrice] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SupplyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Объект:  Table [dbo].[Sellers]    Дата создания скрипта: 05.07.2026 21:50:55 ******/ 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sellers](
	[SellersID] [int] IDENTITY(1,1) NOT NULL,
	[OrderID] [uniqueidentifier] NOT NULL,
	[ProductID] [int] NOT NULL,
	[ProductCount] [int] NOT NULL,
	[DiscountPercent] [decimal](5, 2) NULL,
	[SaleDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[SellersID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Объект:  Table [dbo].[Suppliers]    Дата создания скрипта: 05.07.2026 21:50:55 ******/ 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Suppliers](
	[SupplierID] [int] IDENTITY(1,1) NOT NULL,
	[CompanyName] [varchar](100) NOT NULL,
	[Phone] [varchar](12) NOT NULL,
	[Email] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[SupplierID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Объект:  Index [Client_Phone]    Дата создания скрипта: 05.07.2026 21:50:55 ******/ 
CREATE UNIQUE NONCLUSTERED INDEX [Client_Phone] ON [dbo].[Client]
(
	[Phone] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Объект:  Index [Supplier_Phone]    Дата создания скрипта: 05.07.2026 21:50:55 ******/ 
CREATE UNIQUE NONCLUSTERED INDEX [Supplier_Phone] ON [dbo].[Suppliers]
(
	[Phone] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Client] ADD  DEFAULT (newid()) FOR [ClientID]
GO
ALTER TABLE [dbo].[Client] ADD  DEFAULT (getdate()) FOR [RegistrationDate]
GO
ALTER TABLE [dbo].[Client] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[Orders] ADD  DEFAULT (newid()) FOR [OrderID]
GO
ALTER TABLE [dbo].[Orders] ADD  DEFAULT (getdate()) FOR [OrderDate]
GO
ALTER TABLE [dbo].[Orders] ADD  DEFAULT ((0)) FOR [OrderPrice]
GO
ALTER TABLE [dbo].[Orders] ADD  DEFAULT ((0)) FOR [IsPaid]
GO
ALTER TABLE [dbo].[Products] ADD  DEFAULT (newid()) FOR [ProductGuid]
GO
ALTER TABLE [dbo].[Products] ADD  DEFAULT ((0)) FOR [StockQuantity]
GO
ALTER TABLE [dbo].[Products] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[ProductSupplies] ADD  DEFAULT (getdate()) FOR [SupplyDate]
GO
ALTER TABLE [dbo].[Sellers] ADD  DEFAULT ((0)) FOR [DiscountPercent]
GO
ALTER TABLE [dbo].[Sellers] ADD  DEFAULT (getdate()) FOR [SaleDate]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([ClientID])
REFERENCES [dbo].[Client] ([ClientID])
GO
ALTER TABLE [dbo].[ProductSupplies]  WITH CHECK ADD FOREIGN KEY([ProductID])
REFERENCES [dbo].[Products] ([ProductID])
GO
ALTER TABLE [dbo].[ProductSupplies]  WITH CHECK ADD FOREIGN KEY([SupplierID])
REFERENCES [dbo].[Suppliers] ([SupplierID])
GO
ALTER TABLE [dbo].[Sellers]  WITH CHECK ADD FOREIGN KEY([OrderID])
REFERENCES [dbo].[Orders] ([OrderID])
GO
ALTER TABLE [dbo].[Sellers]  WITH CHECK ADD FOREIGN KEY([ProductID])
REFERENCES [dbo].[Products] ([ProductID])
GO
ALTER TABLE [dbo].[Sellers]  WITH CHECK ADD CHECK  (([ProductCount]>(0)))
GO
USE [master]
GO
ALTER DATABASE [AutoPartsStore] SET  READ_WRITE 
GO



